### ISSUE TITLE
Add an option to set custom string padding char

### ISSUE THREAD

**Issue by edy** [Ericbla/binary-parser#17]
If a length is set and the given string is shorter than the length, the generated code fills the emptyness with spaces.

I have a use case where the padding needs to be `\u0000`.

the workaround is that I use the encoder function to fill the padding with my zeroes:
```
const encodeString = (str) => {
	return str + '\u0000'.repeat(100);
};
...
.string('flash_tel_nr', { stripNull: true, length: 20, trim: true, encoder: encodeString })
```

Also, an option argument passed to the encoder would be nice.

**Comment by Ericbla** [comment]
Hi, This is indeed a good idea.
I've just added a new `padd` option for string encoder

You can use it in your code just as:
```
.string('flash_tel_nr', { stripNull: true, length: 20, trim: true, padd: '\u0000' })
```

The only restriction is that the `padd` string (first character) must be encoded on a single byte.
( from \u0000 to \u007f )

The version 1.4.4 has been published on npm registry
