### ISSUE TITLE
Align encoder options function documentation

### ISSUE THREAD

**Issue by Gauraden** [Ericbla/binary-parser#22]
https://www.npmjs.com/package/binary-parser-encoder#setencoderoptionsopts

In the documentation, there is function "setEncoderOptions", but in the example it's "setEncoderOpts".
The main issue is that there are no such functions in the "Parser" object, but it has "encoderSetOptions".
The function name in the documentation should be aligned with code.

**Comment by Ericbla** [comment]
Thanks for reporting this issue.
I've fixed it in 1.5.3 version
--
Eric
